//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApiFlowerTwo.Models
{
    using Newtonsoft.Json;
    using System;
    using System.Collections.Generic;
    using System.Runtime.Serialization;

    public partial class tbl_favorites
    {
        public int ID { get; set; }
        public int username_ID { get; set; }
        public int product_ID { get; set; }
        public int quantity { get; set; }

        [JsonIgnore]
        [IgnoreDataMember]
        public virtual tbl_products tbl_products { get; set; }
        [JsonIgnore]
        [IgnoreDataMember]
        public virtual tbl_users tbl_users { get; set; }
    }
}
